import { createContext, useState, useEffect, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

interface LanguageProviderProps {
  children: ReactNode;
}

// 翻译文本
const translations = {
  zh: {
    // 导航菜单
    dashboard: '主页',
    employees: '员工',
    customers: '顾客',
    suppliers: '供应商',
    invoices: '发票',
    receipts: '收据',
    reports: '报表',
    settings: '设置',
    home: '首页',
    feedback: '反馈',
    masterData: '主数据',
    humanResources: '人力资源',
    company: '公司',
    project: '项目',
    user: '用户',
    userRole: '用户角色',
    accessRight: '访问权限',

    // 通用UI
    welcome: '欢迎使用管理系统',
    overview: '总览',
    add: '添加',
    edit: '编辑',
    delete: '删除',
    save: '保存',
    cancel: '取消',
    search: '搜索',
    actions: '操作',
    theme: '主题',
    language: '语言',
    logout: '退出登录',
    darkMode: '深色模式',
    lightMode: '浅色模式',
    profile: '个人资料',
    notifications: '通知',
    systemTitle: '管理系统',
    collapseSidebar: '收起侧边栏',
    expandSidebar: '展开侧边栏',
    details: '详情',
    loading: '加载中...',
    print: '打印',
    reset: '重置',
    export: '导出',
    viewDetails: '查看详情',
    addItem: '添加项目',
    chinese: '中文',
    english: 'English',
    pleaseLogin: '请登录',
    login: '登录',
    logoutSuccess: '已成功退出登录',

    // 通用表单字段
    name: '名称',
    email: '邮箱',
    phone: '电话',
    address: '地址',
    date: '日期',
    amount: '金额',
    status: '状态',
    description: '描述',
    code: '代码',
    companyName: '公司名称',
    projectName: '项目名称',
    projectCode: '项目代码',
    startDate: '开始日期',
    endDate: '结束日期',
    username: '用户名',
    roleName: '角色名称',
    permissions: '权限',
    active: '激活',
    inactive: '未激活',
    selectCompany: '选择公司',
    selectRole: '选择角色',
    assignPermissions: '分配权限',
    module: '模块',
    action: '操作',
    completed: '已完成',
    noData: '暂无数据',
    fetchError: '获取数据失败',
    addSuccess: '添加成功',
    addError: '添加失败',
    nameRequired: '请输入名称',
    rowsPerPage: '每页显示',
    page: '页',
    of: '/',
    totalRecords: '条记录',
    avatar: '头像',
    changeAvatar: '更换头像',
    removeAvatar: '移除头像',
    updateSuccess: '更新成功',
    updateError: '更新失败',
    deleteSuccess: '删除成功',
    deleteError: '删除失败',
    confirmDelete: '确认删除',
    confirmDeleteMessage: '确定要删除该记录吗？此操作无法撤销。',

    // 页面描述
    manageCustomers: '管理公司客户信息',
    manageEmployees: '管理公司员工信息',
    manageSuppliers: '管理公司供应商信息',
    manageInvoices: '管理公司发票信息',
    manageReceipts: '管理公司收据信息',
    viewReports: '查看公司的各项数据报表',
    customizeSettings: '自定义系统设置',
    manageFeedback: '管理用户反馈和建议',
    manageCompanies: '管理公司信息',
    manageProjects: '管理项目信息',
    manageUsers: '管理系统用户',
    manageUserRoles: '管理用户角色和权限',
    manageAccessRights: '管理系统访问权限',

    // Dashboard
    totalRevenue: '总收入',
    newCustomers: '新客户',
    pendingInvoices: '待处理发票',
    totalExpenses: '总支出',
    salesTrend: '销售趋势',
    topCustomers: '顶部客户',
    sales: '销售额',

    // Home页面
    welcomeToSystem: '欢迎使用管理系统',
    systemDescription: '这是一个功能完整的管理系统，帮助您高效管理业务流程、客户信息、财务数据等。',
    viewDashboard: '查看仪表盘',
    manageCustomersShort: '管理客户',
    financialManagement: '财务管理',
    financialDescription: '轻松管理发票、收据和财务报告',
    employeeManagement: '员工管理',
    employeeDescription: '管理员工信息和工作安排',
    systemSettings: '系统设置',
    settingsDescription: '配置系统参数和个人偏好',

    // 表格列
    createDate: '创建日期',
    lastPurchase: '最近购买',
    totalSpent: '总消费',
    position: '职位',
    department: '部门',
    hireDate: '入职日期',
    salary: '薪资',
    selectPosition: '选择职位',
    positionManager: '经理',
    positionDeveloper: '开发人员',
    positionDesigner: '设计师',
    positionSales: '销售',
    positionCS: '客服',
    selectDepartment: '选择部门',
    deptTech: '技术部',
    deptMarketing: '市场部',
    deptSales: '销售部',
    deptAdmin: '行政部',
    deptFinance: '财务部',
    idType: '证件类型',
    idNo: '证件号码',
    idCard: '身份证',
    passport: '护照',
    driverLicense: '驾驶证',
    otherIdType: '其他',
    selectIdType: '选择证件类型',
    dueDate: '到期日',
    paymentMethod: '支付方式',
    contact: '联系人',
    category: '类别',
    partnershipStart: '合作开始',

    // 发票
    allStatus: '全部状态',
    draft: '草稿',
    sent: '已发送',
    paid: '已支付',
    overdue: '逾期',
    invoiceItems: '发票项目',
    quantity: '数量',
    unitPrice: '单价',
    totalAmount: '总计金额',
    addInvoice: '添加发票',
    editInvoice: '编辑发票',
    invoiceDetails: '发票详情',
    invoiceInfo: '发票信息',
    invoiceNumber: '发票编号',
    customerInfo: '客户信息',
    customerName: '客户名称',
    customerId: '客户ID',
    selectCustomer: '选择客户',
    clickToAddItems: '点击"添加项目"开始添加发票项目',
    printInvoice: '打印发票',

    // 收据
    addReceipt: '添加收据',
    editReceipt: '编辑收据',
    receiptDetails: '收据详情',
    receiptInfo: '收据信息',
    receiptNumber: '收据编号',
    paymentInfo: '支付信息',
    selectPaymentMethod: '选择支付方式',
    cash: '现金',
    alipay: '支付宝',
    wechat: '微信支付',
    bankCard: '银行卡',

    // 报表
    monthly: '月度',
    quarterly: '季度',
    yearly: '年度',
    totalProfit: '总利润',
    revenueExpenseTrend: '收入与支出趋势',
    revenue: '收入',
    expense: '支出',
    profit: '利润',
    customerDistribution: '客户分布',
    performanceComparison: '绩效对比',
    thisYear: '今年',
    lastYear: '去年',
    individualCustomer: '个人客户',
    smallBusiness: '小型企业',
    mediumBusiness: '中型企业',
    largeBusiness: '大型企业',
    customerSatisfaction: '客户满意度',
    employeeEfficiency: '员工效率',
    costControl: '成本控制',
    marketShare: '市场份额',
    projectCompletion: '项目完成率',
    detailedData: '详细数据',
    period: '期间',
    profitMargin: '利润率',
    total: '总计',
    exportReport: '导出报表',

    // 设置
    appearanceSettings: '外观设置',
    themeColor: '主题颜色',
    generalSettings: '常规设置',
    siteName: '站点名称',
    defaultPage: '默认页面',
    dateFormat: '日期格式',
    timeFormat: '时间格式',
    time24h: '24小时制',
    time12h: '12小时制',
    currency: '货币',
    cny: '人民币 (¥)',
    usd: '美元 ($)',
    eur: '欧元 (€)',
    gbp: '英镑 (£)',
    notificationSettings: '通知设置',
    enableNotifications: '启用通知',
    notificationDescription: '接收系统和业务相关通知',
    autoSave: '自动保存',
    autoSaveDescription: '编辑表单时自动保存更改',
    saveSettings: '保存设置',
    settingsSaved: '设置已保存',
    settingsReset: '设置已重置',

    // 错误和提示
    noMatchingCustomers: '未找到匹配的客户',
    noMatchingEmployees: '未找到匹配的员工',
    noMatchingInvoices: '未找到匹配的发票',
    noMatchingReceipts: '未找到匹配的收据',
    noMatchingSuppliers: '未找到匹配的供应商',
    noMatchingCompanies: '未找到匹配的公司',
    noMatchingProjects: '未找到匹配的项目',
    noMatchingUsers: '未找到匹配的用户',
    noMatchingRoles: '未找到匹配的角色',
    noMatchingAccessRights: '未找到匹配的权限',
    addCustomer: '添加客户',
    editCustomer: '编辑客户',
    customerDetails: '客户详情',
    addEmployee: '添加员工',
    editEmployee: '编辑员工',
    employeeDetails: '员工详情',
    employeeInfo: '员工信息',
    basicInfo: '基本信息',
    contactInfo: '联系信息',
    workInfo: '工作信息',
    idInfo: '证件信息',
    addSupplier: '添加供应商',
    editSupplier: '编辑供应商',
    addCompany: '添加公司',
    editCompany: '编辑公司',
    addProject: '添加项目',
    editProject: '编辑项目',
    addUser: '添加用户',
    editUser: '编辑用户',
    addRole: '添加角色',
    editRole: '编辑角色',
    addAccessRight: '添加权限',
    editAccessRight: '编辑权限',

    // 反馈
    feedbackTitle: '反馈标题',
    feedbackDescription: '反馈描述',
    submitFeedback: '提交反馈',
    feedbackList: '反馈列表',
    uploadImages: '上传图片',
    dragDropImages: '拖拽图片到此处或点击上传',
    maxFileSize: '最大文件大小',
    imagesUploaded: '已上传图片',
    removeImage: '删除图片',
    fileTooLarge: '文件过大，请选择小于 5MB 的图片',
    feedbackSubmitted: '反馈已提交',
    feedbackSubmitFailed: '提交反馈失败',
    enterFeedbackTitle: '请输入反馈标题',
    enterFeedbackDescription: '请详细描述您的反馈或建议',
    noFeedback: '暂无反馈记录',
    createdAt: '创建时间',
    feedbackImages: '反馈图片'
  },
  en: {
    // Navigation menu
    dashboard: 'Dashboard',
    employees: 'Employees',
    customers: 'Customers',
    suppliers: 'Suppliers',
    invoices: 'Invoices',
    receipts: 'Receipts',
    reports: 'Reports',
    settings: 'Settings',
    home: 'Home',
    feedback: 'Feedback',
    masterData: 'Master data',
    humanResources: 'Human Resources',
    company: 'Company',
    project: 'Project',
    user: 'User',
    userRole: 'User role',
    accessRight: 'Access right',

    // Common UI
    welcome: 'Welcome to management system',
    overview: 'Overview',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    search: 'Search',
    actions: 'Actions',
    theme: 'Theme',
    language: 'Language',
    logout: 'Logout',
    darkMode: 'Dark mode',
    lightMode: 'Light mode',
    profile: 'Profile',
    notifications: 'Notifications',
    systemTitle: 'Management system',
    collapseSidebar: 'Collapse sidebar',
    expandSidebar: 'Expand sidebar',
    details: 'Details',
    loading: 'Loading...',
    print: 'Print',
    reset: 'Reset',
    export: 'Export',
    viewDetails: 'View details',
    addItem: 'Add item',
    chinese: '中文',
    english: 'English',
    pleaseLogin: 'Please login',
    login: 'Login',
    logoutSuccess: 'Successfully logged out',

    // Common form fields
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    date: 'Date',
    amount: 'Amount',
    status: 'Status',
    description: 'Description',
    code: 'Code',
    companyName: 'Company name',
    projectName: 'Project name',
    projectCode: 'Project code',
    startDate: 'Start date',
    endDate: 'End date',
    username: 'Username',
    roleName: 'Role name',
    permissions: 'Permissions',
    active: 'Active',
    inactive: 'Inactive',
    selectCompany: 'Select company',
    selectRole: 'Select role',
    assignPermissions: 'Assign permissions',
    module: 'Module',
    action: 'Action',
    completed: 'Completed',
    noData: 'No data',
    fetchError: 'Failed to fetch data',
    addSuccess: 'Added successfully',
    addError: 'Failed to add',
    nameRequired: 'Name is required',
    rowsPerPage: 'Rows per page',
    page: 'Page',
    of: 'of',
    totalRecords: 'records',
    updateSuccess: 'Updated successfully',
    updateError: 'Failed to update',
    deleteSuccess: 'Deleted successfully',
    deleteError: 'Failed to delete',
    confirmDelete: 'Confirm Delete',
    confirmDeleteMessage: 'Are you sure you want to delete this record? This action cannot be undone.',

    // Page descriptions
    manageCustomers: 'Manage company customer information',
    manageEmployees: 'Manage company employee information',
    manageSuppliers: 'Manage company supplier information',
    manageInvoices: 'Manage company invoice information',
    manageReceipts: 'Manage company receipt information',
    viewReports: 'View company data reports',
    customizeSettings: 'Customize system settings',
    manageFeedback: 'Manage user feedback and suggestions',
    manageCompanies: 'Manage company information',
    manageProjects: 'Manage project information',
    manageUsers: 'Manage system users',
    manageUserRoles: 'Manage user roles and permissions',
    manageAccessRights: 'Manage system access rights',

    // Dashboard
    totalRevenue: 'Total revenue',
    newCustomers: 'New customers',
    pendingInvoices: 'Pending invoices',
    totalExpenses: 'Total expenses',
    salesTrend: 'Sales trend',
    topCustomers: 'Top customers',
    sales: 'Sales',

    // Home page
    welcomeToSystem: 'Welcome to management system',
    systemDescription: 'A fully functional management system that helps you efficiently manage business processes, customer information, financial data, and more.',
    viewDashboard: 'View dashboard',
    manageCustomersShort: 'Manage customers',
    financialManagement: 'Financial management',
    financialDescription: 'Easily manage invoices, receipts and financial reports',
    employeeManagement: 'Employee management',
    employeeDescription: 'Manage employee information and work arrangements',
    systemSettings: 'System settings',
    settingsDescription: 'Configure system parameters and personal preferences',

    // Table columns
    createDate: 'Create date',
    lastPurchase: 'Last purchase',
    totalSpent: 'Total spent',
    position: 'Position',
    department: 'Department',
    hireDate: 'Hire Date',
    salary: 'Salary',
    selectPosition: 'Select Position',
    positionManager: 'Manager',
    positionDeveloper: 'Developer',
    positionDesigner: 'Designer',
    positionSales: 'Sales',
    positionCS: 'Customer service',
    selectDepartment: 'Select Department',
    deptTech: 'Technology',
    deptMarketing: 'Marketing',
    deptSales: 'Sales',
    deptAdmin: 'Administration',
    deptFinance: 'Finance',
    idType: 'ID Type',
    idNo: 'ID No.',
    idCard: 'ID card',
    passport: 'Passport',
    driverLicense: 'Driver license',
    otherIdType: 'Other',
    selectIdType: 'Select ID Type',
    dueDate: 'Due date',
    paymentMethod: 'Payment method',
    contact: 'Contact',
    category: 'Category',
    partnershipStart: 'Partnership start',

    // Invoices
    allStatus: 'All status',
    draft: 'Draft',
    sent: 'Sent',
    paid: 'Paid',
    overdue: 'Overdue',
    invoiceItems: 'Invoice items',
    quantity: 'Quantity',
    unitPrice: 'Unit price',
    totalAmount: 'Total amount',
    addInvoice: 'Add invoice',
    editInvoice: 'Edit invoice',
    invoiceDetails: 'Invoice details',
    invoiceInfo: 'Invoice info',
    invoiceNumber: 'Invoice number',
    customerInfo: 'Customer info',
    customerName: 'Customer name',
    customerId: 'Customer ID',
    selectCustomer: 'Select customer',
    clickToAddItems: 'Click "Add item" to start adding invoice items',
    printInvoice: 'Print invoice',

    // Receipts
    addReceipt: 'Add receipt',
    editReceipt: 'Edit receipt',
    receiptDetails: 'Receipt details',
    receiptInfo: 'Receipt info',
    receiptNumber: 'Receipt number',
    paymentInfo: 'Payment info',
    selectPaymentMethod: 'Select payment method',
    cash: 'Cash',
    alipay: 'Alipay',
    wechat: 'WeChat Pay',
    bankCard: 'Bank card',

    // Reports
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    yearly: 'Yearly',
    totalProfit: 'Total profit',
    revenueExpenseTrend: 'Revenue and expense trend',
    revenue: 'Revenue',
    expense: 'Expense',
    profit: 'Profit',
    customerDistribution: 'Customer distribution',
    performanceComparison: 'Performance comparison',
    thisYear: 'This year',
    lastYear: 'Last year',
    individualCustomer: 'Individual customer',
    smallBusiness: 'Small business',
    mediumBusiness: 'Medium business',
    largeBusiness: 'Large business',
    customerSatisfaction: 'Customer satisfaction',
    employeeEfficiency: 'Employee efficiency',
    costControl: 'Cost control',
    marketShare: 'Market share',
    projectCompletion: 'Project completion',
    detailedData: 'Detailed data',
    period: 'Period',
    profitMargin: 'Profit margin',
    total: 'Total',
    exportReport: 'Export report',

    // Settings
    appearanceSettings: 'Appearance settings',
    themeColor: 'Theme color',
    generalSettings: 'General settings',
    siteName: 'Site name',
    defaultPage: 'Default page',
    dateFormat: 'Date format',
    timeFormat: 'Time format',
    time24h: '24-hour',
    time12h: '12-hour',
    currency: 'Currency',
    cny: 'Chinese Yuan (¥)',
    usd: 'US Dollar ($)',
    eur: 'Euro (€)',
    gbp: 'British Pound (£)',
    notificationSettings: 'Notification settings',
    enableNotifications: 'Enable notifications',
    notificationDescription: 'Receive system and business related notifications',
    autoSave: 'Auto save',
    autoSaveDescription: 'Automatically save changes when editing forms',
    saveSettings: 'Save settings',
    settingsSaved: 'Settings saved',
    settingsReset: 'Settings reset',

    // Errors and messages
    noMatchingCustomers: 'No matching customers found',
    noMatchingEmployees: 'No matching employees found',
    noMatchingInvoices: 'No matching invoices found',
    noMatchingReceipts: 'No matching receipts found',
    noMatchingSuppliers: 'No matching suppliers found',
    noMatchingCompanies: 'No matching companies found',
    noMatchingProjects: 'No matching projects found',
    noMatchingUsers: 'No matching users found',
    noMatchingRoles: 'No matching roles found',
    noMatchingAccessRights: 'No matching access rights found',
    addCustomer: 'Add customer',
    editCustomer: 'Edit customer',
    customerDetails: 'Customer details',
    addEmployee: 'Add employee',
    editEmployee: 'Edit employee',
    employeeDetails: 'Employee details',
    employeeInfo: 'Employee info',
    basicInfo: 'Basic info',
    contactInfo: 'Contact info',
    workInfo: 'Work info',
    idInfo: 'ID info',
    addSupplier: 'Add supplier',
    editSupplier: 'Edit supplier',
    addCompany: 'Add company',
    editCompany: 'Edit company',
    addProject: 'Add project',
    editProject: 'Edit project',
    addUser: 'Add user',
    editUser: 'Edit user',
    addRole: 'Add role',
    editRole: 'Edit role',
    addAccessRight: 'Add access right',
    editAccessRight: 'Edit access right',

    // Feedback
    feedbackTitle: 'Feedback title',
    feedbackDescription: 'Feedback description',
    submitFeedback: 'Submit feedback',
    feedbackList: 'Feedback list',
    uploadImages: 'Upload images',
    dragDropImages: 'Drag and drop images here or click to upload',
    maxFileSize: 'Max file size',
    imagesUploaded: 'Images uploaded',
    removeImage: 'Remove image',
    fileTooLarge: 'File too large, please select images under 5MB',
    feedbackSubmitted: 'Feedback submitted',
    feedbackSubmitFailed: 'Failed to submit feedback',
    enterFeedbackTitle: 'Please enter feedback title',
    enterFeedbackDescription: 'Please describe your feedback or suggestions in detail',
    noFeedback: 'No feedback records',
    createdAt: 'Created at',
    feedbackImages: 'Feedback images'
  }
};

export const LanguageContext = createContext<LanguageContextType>({
  language: 'zh',
  setLanguage: () => {},
  t: () => '',
});

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLang = localStorage.getItem('language') as Language;
    return savedLang || 'zh';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}